version: "2"
services:
  neo4j:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4jdata/data:/var/lib/neo4j/data
      - ./neo4jdata/import:/var/lib/neo4j/import
